---
  - name: Play for K3S Kubernetes Cluster
    hosts: pvt
    gather_facts: yes
    become: yes
    become_user: root
    roles:
    - xanmanning.k3s

#ansible-galaxy role install xanmanning.k3s
#ansible-playbook -i invfile Playbooks/6.Roles-Collections/k3s.yml -vvv -e "k3s_become=yes"
#export KUBECONFIG=/etc/rancher/k3s/k3s.yaml  - on server1